/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.view;

import com.controller.ABMContactoController;
import com.controller.ABMController;
import com.util.Constantes;
import com.valueobject.ContactoVO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MEtchegaray
 */
public class MenuContacto extends javax.swing.JFrame {

	
    /**
     * Creates new form MenuContacto2
     */
    public MenuContacto() {
        initComponents();
        
        setTitle("ABM EMPRRESA");				
          
		btnCancelar.doClick();	                
              
    }

  
    
    public void populateUpdateEmpresa(ContactoVO empresaVO) {	
	
			txtCodigoSolicitud.setText(new Integer(empresaVO.getId()).toString());
			txtRazonSocial.setText(empresaVO.getRazonSocial().toString());
			txtDomicilio.setText(empresaVO.getDomicilio().toString());			
		
			/**
			 * Traigo el index de la provincia
			 */
		
			/*int indexProvincia=empresaVO.getProvinciaVO().getId();
			int indexLocalidad=	empresaVO.getLocalidadVO().getId();
			System.out.println(indexProvincia);
			System.out.println(indexLocalidad);
			
			if(indexProvincia==0 || indexLocalidad==0){
				
				comboProvincia1.setSelectedIndex(0);
				comboLocalidad.setSelectedIndex(0);
			}else{
				comboProvincia1.setSelectedIndex(empresaVO.getProvinciaVO().getId()- 1);
				comboLocalidad.setSelectedIndex(empresaVO.getLocalidadVO().getId()-1);	
			}*/
				
			txtWeb.setText(empresaVO.getWeb().toString());
			txtEmail.setText(empresaVO.getEmail().toString());
			TXTTELEFONO.setText(empresaVO.getTelefono().toString());			
			txtfax.setText(empresaVO.getFax().toString());	
			txtWeb.setText(empresaVO.getWeb().toString());			
			
	}
	
    
    public void setEstadoEdicion(boolean isEdicion){	
	
		txtCodigoSolicitud.setEnabled(!isEdicion);		
		txtRazonSocial.setEnabled(isEdicion);
		txtDomicilio.setEnabled(isEdicion);					
		txtEmail.setEnabled(isEdicion);	
                TXTTELEFONO.setEnabled(isEdicion);		
		txtfax.setEnabled(isEdicion);	
		txtWeb.setEnabled(isEdicion);	
	
	
		
		/**
		 * Deshabilito los botones
		 */
		btnSiguiente.setEnabled(!isEdicion);
		btnAnterior.setEnabled(!isEdicion);
		btnPrimero.setEnabled(!isEdicion);
		btnUltimo.setEnabled(!isEdicion);
		btnNuevo.setEnabled(!isEdicion);
		btnGuardar.setEnabled(isEdicion);
		btnCancelar.setEnabled(isEdicion);
		btnModificar.setEnabled(!isEdicion);
		btnEliminar.setEnabled(!isEdicion);
		
	
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoSolicitud = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblSolicitud = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtWeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTTELEFONO = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCodigoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, -1));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        btnPrimero.setText("Primero");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnUltimo.setText("Ultimo");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 80, -1));

        lblSolicitud.setText("Código : ");
        getContentPane().add(lblSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtRazonSocial.setToolTipText("");
        getContentPane().add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, -1));

        jLabel2.setText("Domicilio : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 410, -1));

        jLabel3.setText("Web : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtWeb.setToolTipText("");
        getContentPane().add(txtWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 160, -1));

        jLabel4.setText("E-mail : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        jLabel5.setText("Fax : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txtfax, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, -1));

        jLabel9.setText("Telefono");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        TXTTELEFONO.setToolTipText("");
        getContentPane().add(TXTTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 160, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, 350));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 560, 420));

        jLabel1.setText("Nombre Completo : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        
                                setEstadoEdicion(true);
				
				ABMController  aBMController= new ABMController();
				int ultimoId=0;
				try {
					ultimoId = aBMController.getMaximoValorCampo("contacto", Constantes.ID_CONTACTO);
					//System.out.println("ULTIMO ID:" + ultimoId);
					
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                         	   "Error al Traer el Maximo ID ",
                         	   "Se ha producido un error al hacer la consulta",
                         	   JOptionPane.INFORMATION_MESSAGE);					
				}
				//pongo en blanco todos los campos
				
				txtCodigoSolicitud.setText(ultimoId + 1 + "");	
				txtWeb.setText("");		
				txtRazonSocial.setText("");
				txtRazonSocial.setRequestFocusEnabled(true);	
				txtDomicilio.setText("");	
				txtEmail.setText("");	
				TXTTELEFONO.setText("");			
				txtfax.setText("");	
				txtWeb.setText("");			
				
                                
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        	ContactoVO empresaVO=new ContactoVO();					
				empresaVO.setId(new Integer(txtCodigoSolicitud.getText()).intValue());		
				empresaVO.setRazonSocial(txtRazonSocial.getText());
				empresaVO.setDomicilio(txtDomicilio.getText());
				
			

				try {
					
			
							
				empresaVO.setWeb(txtWeb.getText());
				
				empresaVO.setEmail(txtEmail.getText());				
				
				empresaVO.setTelefono(TXTTELEFONO.getText());
				
				empresaVO.setFax(txtfax.getText());
				
									
					ABMContactoController  aBMEmpresaController=new ABMContactoController();	
								
						boolean validoUpdate=validarCamposObligatorios(evt,empresaVO);	
				
						if (validoUpdate){
							aBMEmpresaController.insertOrUpdate(empresaVO);
							
							btnCancelar.doClick();
						}
						
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						
						JOptionPane.showMessageDialog((Component)evt.getSource(),
	                            "Error al Guardar",
	                            "Se ha producido un error al Guardar",
	                            JOptionPane.INFORMATION_MESSAGE);
						
				}
                                
                                
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
 
        setEstadoEdicion(false);
        txtCodigoSolicitud.setText("0");
        btnUltimo.doClick();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        	setEstadoEdicion(true);				
		txtRazonSocial.setRequestFocusEnabled(true);	
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        	
				ContactoVO empresaVO=new ContactoVO();	
				empresaVO.setId(new Integer(txtCodigoSolicitud.getText()).intValue());					
				ABMContactoController  aBMEmpresaController=new ABMContactoController();				
				try {
					empresaVO=aBMEmpresaController.traerObjetoById(empresaVO.getId());				
					aBMEmpresaController.remove(empresaVO);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                            "Error al Eliminar",
                            "Se ha producido un error al Eliminar",
                            JOptionPane.INFORMATION_MESSAGE);
					
				}
				
				setEstadoEdicion(false);
				btnAnterior.doClick();

        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        		ContactoVO empresaVOIn=new ContactoVO();	
				empresaVOIn.setId(new Integer(txtCodigoSolicitud.getText()).intValue());
                                
                                System.out.println("id de empresa--->:" + empresaVOIn.getId());
				ABMContactoController  aBMEmpresaController=new ABMContactoController();		
				ContactoVO empresaVO=null;
				try {
					empresaVO=aBMEmpresaController.encontrarPosteriorRegistro(empresaVOIn);		
					populateUpdateEmpresa(empresaVO); 					
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                                        "Error al Buscar Siguiente Registro",
                                          "Se ha producido un error al Buscar Siguiente Registros",
                                      JOptionPane.INFORMATION_MESSAGE);
				}

				
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        
        	ContactoVO empresaVOIn=new ContactoVO();	
                                System.out.println("codigo solicitud:" + txtCodigoSolicitud.getText());
				empresaVOIn.setId(new Integer(txtCodigoSolicitud.getText()).intValue());					
				ABMContactoController  aBMEmpresaController=new ABMContactoController();		
				ContactoVO empresaVO=null;
				try {
					empresaVO=aBMEmpresaController.encontrarAnteriorRegistro(empresaVOIn);								
					if(empresaVO!=null){
						populateUpdateEmpresa(empresaVO); 					
					}				
					
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                                         "Error al Buscar Anterior  Registro",
                                     "Se ha producido un error al Buscar Anterior Registros",
                                      JOptionPane.INFORMATION_MESSAGE);
				}

                                
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        // TODO add your handling code here:
        	ContactoVO empresaVOIn=new ContactoVO();	
				empresaVOIn.setId(new Integer(txtCodigoSolicitud.getText()).intValue());					
				ABMContactoController  aBMEmpresaController=new ABMContactoController();		
				ContactoVO empresaVO=null;
				try {
					empresaVO=aBMEmpresaController.encontrarPrimerRegistro();						
					populateUpdateEmpresa(empresaVO); 	
					
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                            "Error al Buscar Primer Registro",
                            "Se ha producido un error al Buscar Primer Registros",
                            JOptionPane.INFORMATION_MESSAGE);
				}

    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        
        int codigo=new Integer(txtCodigoSolicitud.getText()).intValue();		
				ContactoVO empresaVOIn=new ContactoVO();			
				empresaVOIn.setId(codigo);							
				ABMContactoController  aBMEmpresaController=new ABMContactoController();		
				ContactoVO empresaVO=null;										
				try {
					empresaVO=aBMEmpresaController.encontrarUltimoRegistro(empresaVOIn);
					if(empresaVO!=null){
						populateUpdateEmpresa(empresaVO); 	
					}
					
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();					
					/*JOptionPane.showMessageDialog((Component)e.getSource(),
                            "Error al Buscar Ultimo Registro",
                            "Se ha producido un error al Buscar Ultimo Registros",
                            JOptionPane.INFORMATION_MESSAGE);*/
				}


                                
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       // btnCancelar.doClick();	
        
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTTELEFONO;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSolicitud;
    private javax.swing.JTextField txtCodigoSolicitud;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtWeb;
    private javax.swing.JTextField txtfax;
    // End of variables declaration//GEN-END:variables

    private boolean validarCamposObligatorios(ActionEvent evt, ContactoVO empresaVO) {
        
      boolean valido=true;
				
				if (empresaVO.getRazonSocial().equals("")){
					
					valido=false;					
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                            "La razon social no puede estar vacía",
                            "Ingreso Inválido",
                            JOptionPane.INFORMATION_MESSAGE);
				}
				

				if (empresaVO.getDomicilio().equals("")){
					
					valido=false;
					JOptionPane.showMessageDialog((Component)evt.getSource(),
                            "El domicilio no puede estar vacío",
                            "Ingreso Inválido",
                            JOptionPane.INFORMATION_MESSAGE);
				}

				
							
				return valido;

                                
    }

 

  
}
